<?php

namespace Plugin\GrooaWidgets\Widget\ContentSection;

use Plugin\GrooaWidgets\Parsedown;

class Controller extends \Ip\WidgetController
{
    public function generateHtml($revisionId, $widgetId, $data, $skin)
    {
        if (empty($data['title'])) {
            $data['title'] = '[Missing title]';
        }

        if (!empty($data['text'])) {
            $parsedown = new Parsedown();
            $data['text'] = $parsedown->parse($data['text']);
        }

        return parent::generateHtml($revisionId, $widgetId, $data, $skin); // TODO: Change the autogenerated stub
    }

}
